name: Scraper Keno

on:
  schedule:
    # 15h et 22h UTC+2 -> 13h et 20h UTC
    - cron: '0 13 * * *'
    - cron: '0 20 * * *'
  workflow_dispatch:  # permet de lancer manuellement

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraping
        run: python update_data.py

      - name: Commit and push updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/*.json
          git commit -m "Update Keno data [skip ci]" || echo "No changes"
          git push
